sources:
  my-pg-source:
    kind: postgres
    host: db
    port: 5432
    database: toolbox_db
    user: ${USER_NAME}
    password: ${PASSWORD}
  swag-api:
    kind: http
    baseUrl: http://${SWAG_API_HOST}:8000
    timeout: 10s # default to 30s
tools:
  search-hotels-by-name:
    kind: postgres-sql
    source: my-pg-source
    description: Search for hotels based on name.
    parameters:
      - name: name
        type: string
        description: The name of the hotel.
    statement: SELECT * FROM hotels WHERE name ILIKE '%' || $1 || '%';
  search-hotels-by-location:
    kind: postgres-sql
    source: my-pg-source
    description: Search for hotels based on location.
    parameters:
      - name: location
        type: string
        description: The location of the hotel.
    statement: SELECT * FROM hotels WHERE location ILIKE '%' || $1 || '%';
  book-hotel:
    kind: postgres-sql
    source: my-pg-source
    description: >-
       Book a hotel by its ID. If returned hotel booked is 1, then the hotel is successfully booked, otherwise it is not.
    parameters:
      - name: hotel_id
        type: string
        description: The ID of the hotel to book.
    statement: >- 
      UPDATE hotels SET booked = B'1' WHERE id = $1 RETURNING id, booked;
  update-hotel:
    kind: postgres-sql
    source: my-pg-source
    description: >-
      Update a hotel's check-in and check-out dates by its ID. Returns a message
      indicating  whether the hotel was successfully updated or not.
    parameters:
      - name: hotel_id
        type: string
        description: The ID of the hotel to update.
      - name: checkin_date
        type: string
        description: The new check-in date of the hotel.
      - name: checkout_date
        type: string
        description: The new check-out date of the hotel.
    statement: >-
      UPDATE hotels SET checkin_date = CAST($2 as date), checkout_date = CAST($3
      as date) WHERE id = $1;
  cancel-hotel:
    kind: postgres-sql
    source: my-pg-source
    description: Cancel a hotel by its ID.
    parameters:
      - name: hotel_id
        type: string
        description: The ID of the hotel to cancel.
    statement: UPDATE hotels SET booked = B'0' WHERE id = $1 RETURNING id, booked;
  debug-swag-api:
    kind: http
    source: swag-api
    method: GET
    path: /debug
    description: Tool to send debug requests to the API
toolsets:
  my-toolset:
    - search-hotels-by-name
    - search-hotels-by-location
    - book-hotel
    - update-hotel
    - cancel-hotel
  swag-api:
    - debug-swag-api
